version: '2'

services:
  node:
    image: node:8
    ports:
      - 127.0.0.1:3001:3001
    volumes:
      - ./:/srv
    working_dir: /srv
    entrypoint: /bin/sh
    command:
      - -c
      - npm install && npm run web-dev
